Repository starkblaze01/Algorithms-Cheatsheet-Resources, pull requests merged in 2019-10, with the labels that each got.

#6 adds manachar's algorithm
  Manachar_Algorithm/manachar.cpp
Labels: hacktoberfest

#7 Adds Fermat's Theorem
  Fermat's_Little_Theorem/Fermat's theorem.cpp
Labels: hacktoberfest

#10 Added Breadth first search algorithm in graphs
  Breadth_First_Searh/bfs.py
Labels: hacktoberfest

#11 Create Insertion Sort
  Sorts/Insertion Sort.cpp
Labels: hacktoberfest

#9 adds coin change problem
  coin_change_algorithm/coin change.cpp
Labels: hacktoberfest

#13 Created "searching-in-a-sorted-matrix.py"
  Searching-In-Sorted-Matrix/searching-in-sorted-matrix.py
Labels: hacktoberfest

#14 Created preOrderBST.java
  preOrderBST.java
Labels: hacktoberfest

#18 Added Maximum Contiguous Subarray Sum Kadane's Algorithm
  Maximum Contiguous Subarray Sum Kadane's Algorithm/maxsubarraysum.py
Labels: hacktoberfest

#20 Added GCD in JavaScript
  GCD/gcd.js
Labels: hacktoberfest

#21 Added LCM in JavaScript
  LCM/lcm.js
Labels: hacktoberfest

#23 Added Totient Function
  TotientFunction/totient.js
Labels: hacktoberfest

#25 Added Combination
  Combination/combination.js
Labels: hacktoberfest

#27 Added Prim's Algorithm
  prims_algorithm/prims.cpp
Labels: hacktoberfest

#28 Added recursive implementation of DFS in Python
  Depth_First_Search/dfs_recursive.py
Labels: hacktoberfest

#29 Create kruskal.CPP
  Kruskal's Algorithm/kruskal.CPP
Labels: hacktoberfest

#31 Contribuição com códigos java de validação de CPF, fiboanacci e número triangular!
  CodigosUteis/.classpath
  CodigosUteis/.gitignore
  CodigosUteis/.project
  CodigosUteis/.settings/org.eclipse.jdt.core.prefs
  CodigosUteis/src/classes/Fibonacci.java
  CodigosUteis/src/classes/ValidadorCPF.java
  CodigosUteis/src/classes/ValidadorNumTri.java
  CodigosUteis/src/classes/index.java
Labels: hacktoberfest

#30 Implemented Dijkstra's Algorithm for Single-Source Shortest-Path
  Dijkstra/dijkstra.py
Labels: hacktoberfest

#32 Fibonacci linear (?) recursion in python.
  fibonacci recursion/fibonacci.py
Labels: hacktoberfest

#33 Create ford-fulkerson-algorithm.cpp
  Ford-Fulkerson Algorithm/ford-fulkerson-algorithm.cpp
Labels: hacktoberfest

#34 Two Client Single Server Architecture in Java
  Client-Server-Architecture-Java/Client1.java
  Client-Server-Architecture-Java/Client2.java
  Client-Server-Architecture-Java/Server.java
Labels: hacktoberfest

#36 adding iterative_deepening_search
  iterative_deepening_search/iterative_deepening_search.cpp
Labels: hacktoberfest

#37 Added Doubly Linked Dynamic List
  Doubly_Linked_List/List.h
  Doubly_Linked_List/main.cpp
Labels: hacktoberfest

#38 Golang Sieve of Eratosthenes
  Sieve-Of-Eratosthenes/Golang/SieveOfEratosthenes.go
Labels: hacktoberfest

#39 Algorithm for Singly Linked List.
  SinglyLinkedList/SinglyLinkedList.py
Labels: hacktoberfest

#40 Golang Kadane's Algorithm
  Kadanes-Algorithm/Golang/kadanes.go
Labels: hacktoberfest

#46 Adds Radix-Sort
  Radix_Sort/radix.cpp
Labels: hacktoberfest

#47 Added Karatsuba algorithm
  karatsuba.cpp
Labels: hacktoberfest

#48 added bfs in c++
  Breadth_First_Search/bfs.cpp
  Breadth_First_Search/bfs.py
Labels: hacktoberfest

#49 added Islands in a graph using DFS
  n_island.cpp
Labels: hacktoberfest

#50 Added DP solution of finding out min cost path in c++
  Dynamic Programming/min_cost_path.cpp
Labels: hacktoberfest

#52 sqrt function algorithm.
  sqrt_function_algorithm/README.md
  sqrt_function_algorithm/sqrt_cplusplus.cpp
Labels: hacktoberfest

#58 Added Heap sort, radix sort and insertion sort
  Heap_Sort/heapsort.cpp
  Insertion_Sort/insertion.py
Labels: hacktoberfest

#60 Added "finding ith smallest element code"
  Finding ith smallest element/finding ith smallest element.c
Labels: hacktoberfest

#61 Update README.md
  README.md
Labels: hacktoberfest

#62 Added the N queen algorithm with brute force in c++ using 6x6 as example
  6 queens brute force algorithm/main.cpp
Labels: hacktoberfest

#64 added merge sort algorithm in C++
  merge_sort_algorithm/merge-sort-using-c++.cpp
Labels: hacktoberfest

#63 Updated README.md
  README.md
Labels: hacktoberfest

#67 Added topological sorting
  Topological_Sort/topological_sort.cpp
Labels: hacktoberfest

#69 Added cpp solution for Tower of Hanoi
  TowerOfHanoi/ToH.cpp
Labels: hacktoberfest

#70 Create TimSort.java
  TimSort/TimSort.java
Labels: hacktoberfest

#71 Added prim's algorithm in c
  Dijkstra/dijsktra.c
  prims_algorithm/prims.c
Labels: hacktoberfest

#72 Factorial using Recursion
  Factorial.C
Labels: hacktoberfest

#76 Program to find Factorial of any integer
  FactorialBigIntegers.cpp
Labels: hacktoberfest

#77 Adding tower of hanoi in c
  TowerOfHanoi/towerOfHanoi.c
Labels: hacktoberfest

#57 Added folder with python code to calculate mean of input array
  Mean/calMean.py
Labels: changes-requested, invalid

#59 Different ques based on bin_search
  Binary_search/ceil_floor.cpp
  Binary_search/findNumberOfRotations.cpp
  Binary_search/flyBinSearch.cpp
  Binary_search/search_in_rotated_array.cpp
Labels: hacktoberfest, invalid

#80 added the dfs_iterative python version
  Depth_First_Search/dfs_iterative.py
Labels: hacktoberfest

#82 binary tree python
  binary_tree/binary_tree_traversal.py
Labels: hacktoberfest

#83 Python Implementation of some algorithms
  BoggleSearch_Py/BoggleSearch.py
  BoggleSearch_Py/README.md
  Calculator_Py/Calculator.py
  Calculator_Py/README.md
Labels: hacktoberfest

#84 Added Bellman_Ford Algorithm
  Bellman-Ford/Bellman_Ford.cpp
Labels: hacktoberfest

#85 Added nth term fibonacci.py
  nth term fibonacci/nth term fibonacci.py
Labels: hacktoberfest
