Repository starkblaze01/Algorithms-Cheatsheet-Resources, pull requests merged in 2020-10, with the labels that each got.

#271 Added Mergesort in Js
  JavaScript/Heapsort/Heapsort.js
  JavaScript/MergeSort/Mergesort.js
Labels: changes-requested

#281 Adding 2048
  Python/2048/README.md
  Python/2048/logic.py
  Python/2048/puzzle.py
Labels: awesome

#269 added heapsort.java
  Java/Sorting Algorithms/HeapSort/HeapSort.java
Labels: changes-requested

#275 Added longest_common_subsequence.cpp
  cpp/Dynamic Programming/longest_common_subsequence.cpp
Labels: changes-requested

#291 Nut556
  cpp/Dynamic Programming/kadane_algo.cpp
Labels: changes-requested

#294 Ali
  JavaScript/BubbleSort/bubbleSort.js
Labels: changes-requested

#314 Add script to quick print class attributes
  Python/print_class_attributes.py
Labels: changes-requested

#320 added JumpSearch Java algorithm
  Java/Searching/JumpSearch.java
Labels: hacktoberfest-accepted

#321 Added Encryption Algorithms
  Python/EncryptionAlgo_Py/AffineCipher.py
  Python/EncryptionAlgo_Py/CaesarCipher.py
  Python/EncryptionAlgo_Py/HillCipher.py
  Python/EncryptionAlgo_Py/ROT13.py
  Python/EncryptionAlgo_Py/TranspositionCipher.py
  Python/EncryptionAlgo_Py/XorCipher.py
Labels: hacktoberfest-accepted

#325 added pygames
  Python/py_games/Blackjack.ipynb
  Python/py_games/TicTacToe.ipynb
Labels: hacktoberfest-accepted
