Repository starkblaze01/Algorithms-Cheatsheet-Resources, pull requests merged in 2022-10, with the labels that each got.

#382 Roadmap on 'Entering the Programming World' added
  Roadmaps/Entering the Programming world/README.md
Labels: hacktoberfest, hacktoberfest2022

#384 timsort.py
  Python/Sorting Algorithms/timsort.py
Labels: hacktoberfest, hacktoberfest2022

#389 Hashing Algorithm
  Java/CodigosUteis/.project
  Java/CodigosUteis/.settings/org.eclipse.jdt.core.prefs
  Java/hashing/MD5.java
  Java/hashing/SHA256.java
  Java/hashing/TwoSum.java
Labels: hacktoberfest, hacktoberfest2022

#390 Algorithms spelling.
  CONTRIBUTING.md
Labels: invalid-hacktoberfest

#396 Create Bucket-Sort.c
  c/Sorting Algorithms/Bucket-Sort.c
Labels: hacktoberfest, hacktoberfest2022

#397 added popular python package sources to README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#399 I have added some basic graph traversal algorithms.
  Python/Opencv_Pathfinding_Algorithms/Image.png
  Python/Opencv_Pathfinding_Algorithms/astar.py
  Python/Opencv_Pathfinding_Algorithms/bfs.py
  Python/Opencv_Pathfinding_Algorithms/dfs.py
  Python/Opencv_Pathfinding_Algorithms/dijkstra.py
  Python/Opencv_Pathfinding_Algorithms/readme.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#400 Added decimal to binary
  Python/decimal-to-binary.py
Labels: hacktoberfest, hacktoberfest2022

#403 Agglomerative Clustering added
  Python/Agglomerative Clustering/Agglomerative.ipynb
  Python/Agglomerative Clustering/ReadMe.md
  Python/Agglomerative Clustering/agglodata.csv
  Python/Agglomerative Clustering/agglomerative.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#406 I would like to add a another way for visualising the given algorithm.
  Python/Opencv_Pathfinding_Algorithms/Maze/Astar_for_maze.py
  Python/Opencv_Pathfinding_Algorithms/Maze/Dijkstra_for_maze.py
  Python/Opencv_Pathfinding_Algorithms/Maze/bfs_final_for_maze.py
  Python/Opencv_Pathfinding_Algorithms/Maze/dfs_final_for_maze.py
  Python/Opencv_Pathfinding_Algorithms/Maze/dfsforMaze_output.png
  Python/Opencv_Pathfinding_Algorithms/Maze/readme.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#410 Adding Hangman Game
  Python/Hangman_game.py/Hangman.py
  Python/Hangman_game.py/words.txt
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#412 Finding square root more precisely
  cpp/sqrt_function_algorithm/Find_Decimal_in_SquareRoot.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#414 Added Counting Sort in C language
  c/Sorting Algorithms/countingSort.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#415 Well-handwritten notes on Time and Space complexity.
  Time and Space Complexity.pdf
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#420 Restructe file location
  Roadmaps/Entering the Programming world/Getting Started.md
  Roadmaps/Entering the Programming world/Time and Space Complexity.pdf
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#421 Adds Compiler vs Interpreter Note
  Roadmaps/Entering the Programming world/Compiler_vs_Interpreter.pdf
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#423 Roadmap/js vs python
  Roadmaps/Frameworks/JSvsPython.png
Labels: hacktoberfest, hacktoberfest2022

#422 distance in 3d space
  Python/cartesian to polar.py
  Python/distance in 3D space.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#409 Create Intersection_in_linkedlist.py
  Python/Intersection_in_linkedlist.py
Labels: invalid, changes-requested

#425 Added Recursive Palindrome in Python
  Python/RecursivePalindrome.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
